/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sises.vista;

import javax.swing.JOptionPane;
import ucr.ac.cr.sises.controlador.ControllerStudent;

/**
 *
 * @author galagarza
 */
public class FrmStudent extends javax.swing.JFrame {

    /**
     * Creates new form FrmEstudiantes
     */
    public FrmStudent() {
        initComponents();
    }
    
    public static void message(String msj){
        JOptionPane.showMessageDialog(null, msj);
    }
    
    public void setController(ControllerStudent controller){
        this.panelBotones1.listen(controller);
        this.panelEstudiante1.listener(controller);
        this.panelTabla1.listener(controller);
    }
    public PanelStudent getPanelStudent(){
        return this.panelEstudiante1;
    }
    public PanelTable getPanelTable(){
        return this.panelTabla1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEstudiante1 = new ucr.ac.cr.sises.vista.PanelStudent();
        panelTabla1 = new ucr.ac.cr.sises.vista.PanelTable();
        panelBotones1 = new ucr.ac.cr.sises.vista.PanelButtons();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelEstudiante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));
        getContentPane().add(panelTabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 410));
        getContentPane().add(panelBotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.sises.vista.PanelButtons panelBotones1;
    private ucr.ac.cr.sises.vista.PanelStudent panelEstudiante1;
    private ucr.ac.cr.sises.vista.PanelTable panelTabla1;
    // End of variables declaration//GEN-END:variables
}
