/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sises.vista;

import java.awt.event.MouseListener;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author galagarza
 */
public class PanelTable extends javax.swing.JPanel {

    /**
     * Creates new form PanelTabla
     */
    TableRowSorter<DefaultTableModel> sorter;

    public PanelTable() {
        initComponents();
    }

    public void setTable(String[][] matriz) {
        this.jScrollPane1.setViewportView(this.tblDataStudent);
        DefaultTableModel modelo = new DefaultTableModel(matriz, new String[]{"Carnet", "Nombre", "Edad", "Teléfono", "Dirección"});
        this.tblDataStudent.setModel(modelo);
        this.tblDataStudent.setAutoCreateRowSorter(true);
        this.sorter = new TableRowSorter<>(modelo);
        this.tblDataStudent.setRowSorter(sorter);
    }
    
    public void listener(MouseListener controller){
        this.tblDataStudent.addMouseListener(controller);
    }
    
    public String[] getRow(){
        String[] dataRow=new String[5];
        int selectedRow=this.tblDataStudent.getSelectedRow();
        for (int i = 0; i < this.tblDataStudent.getColumnCount(); i++) {
            dataRow[i]=String.valueOf(this.tblDataStudent.getValueAt(selectedRow, i));
        }
        return dataRow;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataStudent = new javax.swing.JTable();
        txtFiltrar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboxColumna = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 255, 204));

        tblDataStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Carnet", "Nombre", "Edad", "Teléfono", "Dirección"
            }
        ));
        jScrollPane1.setViewportView(tblDataStudent);

        txtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltrarKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 3, 13)); // NOI18N
        jLabel1.setText("Filtrar:");

        cboxColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Carnet", "Nombre", "Edad" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboxColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cboxColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarKeyReleased
        // TODO add your handling code here:
        try {
            if (this.cboxColumna.getSelectedItem().equals("Todas")) {
                this.sorter.setRowFilter(RowFilter.regexFilter("(?i)" + this.txtFiltrar.getText()));
            } else if (this.cboxColumna.getSelectedItem().equals("Carnet")) {
                this.sorter.setRowFilter(RowFilter.regexFilter("(?i)" + this.txtFiltrar.getText(), 0));
            } else if (this.cboxColumna.getSelectedItem().equals("Nombre")) {
                this.sorter.setRowFilter(RowFilter.regexFilter("(?i)" + this.txtFiltrar.getText(), 1));
            } else {
                this.sorter.setRowFilter(RowFilter.regexFilter("(?i)" + this.txtFiltrar.getText(), 2));
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtFiltrarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxColumna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataStudent;
    private javax.swing.JTextField txtFiltrar;
    // End of variables declaration//GEN-END:variables
}
