/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sises.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author galagarza
 */
public class PanelButtons extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotones
     */
    public PanelButtons() {
        initComponents();
    }
    
    public void listen(ActionListener controller){
        this.btnAtras.addActionListener(controller);
        this.btnEditar.addActionListener(controller);
        this.btnEliminar.addActionListener(controller);
        this.btnGuardar.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/285657_floppy_guardar_save_icon.png"))); // NOI18N
        btnGuardar.setActionCommand("add");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/285631_notepad_icon.png"))); // NOI18N
        btnEditar.setActionCommand("edit");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1814090_delete_garbage_trash_icon.png"))); // NOI18N
        btnEliminar.setActionCommand("delete");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/299061_house_icon.png"))); // NOI18N
        btnAtras.setActionCommand("close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnAtras))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    // End of variables declaration//GEN-END:variables
}
